inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Metrics/AbcSize:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericLiterals:
  Strict: false

Style/RescueStandardError:
  EnforcedStyle: explicit

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false