---
  language: ruby
  rvm:
    - 2.7.2
  cache:
    - bundler
    - yarn
  services:
    - postgresql
  before_install:
    - gem install bundler -v 2.1.4
    - nvm install --lts
  before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres
    - bundle install --jobs=3 --retry=3
    - yarn
    - bundle exec rake db:create
    - bundle exec rake db:migrate
  script:
    - bundle exec rake spec